### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 no such table: seo

### ISSUE THREAD

**Issue by alsarem-official** [ralphjsmit/laravel-filament-seo#30]
SQLSTATE[HY000]: General error: 1 no such table: seo
SELECT
  *
FROM
  "seo"
WHERE
  "seo"."model_type" = App \ Models \ Brand
  AND "seo"."model_id" = 2
  AND "seo"."model_id" IS NOT NULL
limit
  1

**Comment by ralphjsmit** [comment]
Hi! You need to publish and run the migration.

**Comment by ralphjsmit** [comment]
https://github.com/ralphjsmit/laravel-seo?tab=readme-ov-file#installation
